ENV['VAGRANT_EXPERIMENTAL'] = 'typed_triggers'

require 'open3'

VM_CPU = 4
VM_MEMORY_GB = 4
VM_ROOT_DISK_SIZE_GB = 128

Vagrant.configure('2') do |config|
  config.vm.box = 'proxmox-ve-v8-amd64'
  #config.vm.box = 'proxmox-ve-uefi-amd64'

  config.vm.provider :virtualbox do |vb|
    vb.linked_clone = true
    vb.memory = VM_MEMORY_GB*1024
    vb.cpus = VM_CPU
    vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end

  ip = '10.10.10.2'
  config.vm.network :private_network,
    ip: ip,
    auto_config: false,
    libvirt__dhcp_enabled: false,
    libvirt__forward_mode: 'none'
  config.vm.provision :shell, path: 'provision.sh', args: ip
  config.vm.provision :shell, path: 'provision-pveproxy-certificate.sh', args: ip
  config.vm.provision :shell, path: 'provision-containers.sh', args: ip
  config.vm.provision :shell, path: 'summary.sh', args: ip
end
